version: '3.8'
services:
  web:
    image: nginx:alpine
    volumes:
      - ./:/usr/share/nginx/html:ro
    restart: always
    networks:
      - proxy-network
    user: root
    command: ["nginx", "-g", "daemon off;"]

networks:
  proxy-network:
    external: true
