version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: meu-site-nginx
    volumes:
      - ./:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    networks:
      - proxy-network

  php:
    image: php:8.2-fpm
    container_name: meu-site-php
    volumes:
      - ./:/var/www/html:ro
    restart: always
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
