version: '3.8'
services:
  web:
    image: php:8.2-apache
    container_name: udianix-site-apache
    volumes:
      - ./:/var/www/html
    restart: always
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
